//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Sources/Input/VehicleInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace CrazyRacing.Input
{
    public partial class @VehicleInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @VehicleInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""VehicleInput"",
    ""maps"": [
        {
            ""name"": ""Vehicle"",
            ""id"": ""ae414714-9422-4ca5-b637-c6834fcc146a"",
            ""actions"": [
                {
                    ""name"": ""RecoveredVehicle"",
                    ""type"": ""Button"",
                    ""id"": ""04e56752-e3fe-4214-bb5c-30d3ca14e102"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1a084171-f4f0-4f78-9323-b47a527a9ab8"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecoveredVehicle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Vehicle
            m_Vehicle = asset.FindActionMap("Vehicle", throwIfNotFound: true);
            m_Vehicle_RecoveredVehicle = m_Vehicle.FindAction("RecoveredVehicle", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Vehicle
        private readonly InputActionMap m_Vehicle;
        private IVehicleActions m_VehicleActionsCallbackInterface;
        private readonly InputAction m_Vehicle_RecoveredVehicle;
        public struct VehicleActions
        {
            private @VehicleInput m_Wrapper;
            public VehicleActions(@VehicleInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @RecoveredVehicle => m_Wrapper.m_Vehicle_RecoveredVehicle;
            public InputActionMap Get() { return m_Wrapper.m_Vehicle; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(VehicleActions set) { return set.Get(); }
            public void SetCallbacks(IVehicleActions instance)
            {
                if (m_Wrapper.m_VehicleActionsCallbackInterface != null)
                {
                    @RecoveredVehicle.started -= m_Wrapper.m_VehicleActionsCallbackInterface.OnRecoveredVehicle;
                    @RecoveredVehicle.performed -= m_Wrapper.m_VehicleActionsCallbackInterface.OnRecoveredVehicle;
                    @RecoveredVehicle.canceled -= m_Wrapper.m_VehicleActionsCallbackInterface.OnRecoveredVehicle;
                }
                m_Wrapper.m_VehicleActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @RecoveredVehicle.started += instance.OnRecoveredVehicle;
                    @RecoveredVehicle.performed += instance.OnRecoveredVehicle;
                    @RecoveredVehicle.canceled += instance.OnRecoveredVehicle;
                }
            }
        }
        public VehicleActions @Vehicle => new VehicleActions(this);
        public interface IVehicleActions
        {
            void OnRecoveredVehicle(InputAction.CallbackContext context);
        }
    }
}
